language: node_js
node_js: 9.4.0
services: postgresql
before_script:
- psql -c 'CREATE DATABASE leaderboard;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 4uLgY+AdXPnl9Y/5P5fCKeyWov1bdLTb7mzrh3JGQNyjdaoKfx07lHU4ZgOPD9kR/J5DdYjPnb7XiRZSNL0zxdq0RGu01P7mNOJMUDxFuokXOSJgvZYs8k0DgGLRPMsmKSTDRPReAbd+F7ud+lFaXhlZWJdm8o2t+kScRNST44XcZynTGb7OOMapUTYkQikKWPMc5KAcTs7Qjn0gcsQh2hzbWQeZz2Itg3sNNweUBmi1o3+7/lSvjh0V5iMG4B4SP2dPuEUf0rOhPRYm+pMcmIXOlfT4LCxsAeV7Vbd5+vnoxFx1cbXsJMshlZmZ4SXq+DBkXKt/8Z3MWWTlycgI5DceBcWIakxYeG3/ZRwh6XmfwOao0J6mfVh3Tj9TjpjZBckggbhf1sb6WjILbRWE7yCzKSmSvGqyiuDrw+JNFzvxO4Lznb30MUT2vAPiGAPpOIuui/0bIe06BuU0Ah2BSUnpBLq86XRQBzbWfsy8XFZ8iKjDCGmx9QT1s+2xXRmxVgou7yupaoE9/eC0ZWjWQP9DgeHKxNLkrJ3m9ikKraVAwKBtf3nGjgk8ubk99NCj4K1NRivk1SDRhPmVkFq3x8E4j47FYiN2DRbDienVA5HUeQpVUVxyvTb76XadonwSUOvik0WWIkqzv8/6rOpcbEe0DnrrGksdkyIxGbKwqPs=
  skip_cleanup: true
